.PHONY: db-start db-stop db-restart db-status start-server

db-start:
	sudo service postgresql start

db-stop:
	sudo service postgresql stop

db-restart:
	sudo service postgresql restart

db-status:
	sudo service postgresql status

start-server:
	go run main.go