import * as React from 'react';
import { TextField } from "@mui/material";
import './VhAssistant.css';
import Button from '@mui/material/Button';
import Stack from '@mui/material/Stack';

function VhAssistant() {

  const autoGeneratedText = "This is some auto-generated text that goes in the TextField.(kjshdfksjhdfkjshdflakjshdfklasjhdlfksjhdfkjashdkfjhaskldjfhlkwjehrfiuerhfierufhjahlskdjhaskljdcnaskldjcnasdlhbvdfjbvhadkfjbvhsdkjhfbvskdjhfbvsjkdhfbvsjkfbvhs)";

  return (
  
    <div>
    
      <TextField
            id="Input"
            type="text"
            label="Ask VH Assistant..."
            multiline
            style={{ marginTop: "0%", marginLeft: "20%", marginRight: "25%" , width: "780px"}}
            halfWidth
          />  

          <Stack spacing={2} direction="row" style={{ marginLeft: "20%"}}>
            <Button variant="contained" endIcon={<sendIcon/>} style={{ marginTop: "2%", backgroundColor: "#243047", marginRight: "75%" }}>
             Send Query
           </Button>
          </Stack>


          <TextField
            id="Response"
            label="Response"
            multiline
            value={autoGeneratedText}
            InputProps={{readOnly: true, }}
            style={{ marginLeft: "10%", marginTop: "5%" ,width: "1000px", marginRight: "10%"}}
           
         />
          

      </div>

    
  );
}

export default VhAssistant;
