import * as React from 'react';
import { TextField } from "@mui/material";
import './VhAssistant.css';
import Button from '@mui/material/Button';
import Stack from '@mui/material/Stack';

function VhAssistant() {

  const autoGeneratedText = "This is some auto-generated text that goes in the TextField.(kjshdfksjhdfkjshdflakjshdfklasjhdlfksjhdfkjashdkfjhaskldjfhlkwjehrfiuerhfierufhjahlskdjhaskljdcnaskldjcnasdlhbvdfjbvhadkfjbvhsdkjhfbvskdjhfbvsjkdhfbvsjkfbvhs)";

  return (
  
    <div>
      <div className="topbar">Welcome to the Virtual Horizon Assistant. The VH Assistant is an AI based chatbot helping you in asking different sort of questions in order to resolve your queries.</div>
      
      
      <TextField
            id="Input"
            type="text"
            label="Ask VH Assistant..."
            multiline
            style={{ marginTop: "10%", marginLeft: "25%", marginRight: "25%" , width: "700px"}}
            halfWidth
          />  

          <Stack spacing={2} direction="row" style={{ marginLeft: "25%"}}>
            <Button variant="contained" endIcon={<sendIcon/>} style={{ marginTop: "2%", backgroundColor: "#243047", marginRight: "75%" }}>
             Send Query
           </Button>
          </Stack>


          <TextField
            id="Response"
            label="Response"
            multiline
            value={autoGeneratedText}
            InputProps={{readOnly: true, }}
            style={{ marginLeft: "10%", marginTop: "5%" ,width: "1000px", marginRight: "10%"}}
           
         />
          

      </div>

    
  );
}

export default VhAssistant;
